Add ssh key setup script

diff --git a/configure_dotfiles b/configure_dotfiles
--- a/configure_dotfiles
+++ b/configure_dotfiles
@@ -1,22 +1,39 @@
-#! /bin/sh
+#! /bin/bash
+
+linkfile()
+{
+    if [ -e $2 ]; then
+        mv $2 ~/oldfiles
+    fi
+    ln -s $1 $2
+}
+
+if [ ! -d ~/oldfiles ]; then
+    mkdir -p ~/oldfiles
+else
+    echo "Setup script has already been run, aborting."
+    exit 1
+fi
+
 git submodule init
 git submodule update
 cd ~/
 #ln -s ~/dotfiles/bashrc ~/.bashrc
-ln -s ~/dotfiles/vimrc ~/.vimrc
-ln -s ~/dotfiles/vim ~/.vim
-ln -s ~/dotfiles/gvimrc ~/.gvimrc
-ln -s ~/dotfiles/gitignore_global ~/.gitignore_global
-ln -s ~/dotfiles/gitconfig ~/.gitconfig
-ln -s ~/dotfiles/xinitrc ~/.xinitrc
-ln -s ~/dotfiles/Xresources ~/.Xresources
-ln -s ~/dotfiles/zprofile ~/.zprofile
-ln -s ~/dotfiles/xprofile ~/.xprofile
-ln -s ~/dotfiles/zshrc ~/.zshrc
-mkdir ~/.config
-mkdir ~/tmp
-ln -s ~/dotfiles/bspwm ~/.config/bspwm
-ln -s ~/dotfiles/sxhkd ~/.config/sxhkd
-ln -s ~/dotfiles/weechat ~/.config/weechat
-ln -s ~/dotfiles/pianobar ~/.config/pianobar
-ln -s ~/dotfiles/Scripts ~/Scripts
+linkfile ~/dotfiles/vimrc ~/.vimrc
+linkfile ~/dotfiles/vim ~/.vim
+linkfile ~/dotfiles/gvimrc ~/.gvimrc
+linkfile ~/dotfiles/gitignore_global ~/.gitignore_global
+linkfile ~/dotfiles/gitconfig ~/.gitconfig
+linkfile ~/dotfiles/xinitrc ~/.xinitrc
+linkfile ~/dotfiles/Xresources ~/.Xresources
+linkfile ~/dotfiles/zprofile ~/.zprofile
+linkfile ~/dotfiles/xprofile ~/.xprofile
+linkfile ~/dotfiles/zshrc ~/.zshrc
+mkdir -p ~/.config
+mkdir -p ~/tmp
+linkfile ~/dotfiles/bspwm ~/.config/bspwm
+linkfile ~/dotfiles/sxhkd ~/.config/sxhkd
+linkfile ~/dotfiles/weechat ~/.config/weechat
+linkfile ~/dotfiles/pianobar ~/.config/pianobar
+linkfile ~/dotfiles/Scripts ~/Scripts
+exit 0
